#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cd mesh

rm -rf 0
cleanCase

cd ..

# ----------------------------------------------------------------- end-of-file


